// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notify.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_notify_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_notify_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "base.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_notify_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_notify_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_notify_2eproto;
namespace chat_ns {
class NotifyFriendAddApply;
struct NotifyFriendAddApplyDefaultTypeInternal;
extern NotifyFriendAddApplyDefaultTypeInternal _NotifyFriendAddApply_default_instance_;
class NotifyFriendAddProcess;
struct NotifyFriendAddProcessDefaultTypeInternal;
extern NotifyFriendAddProcessDefaultTypeInternal _NotifyFriendAddProcess_default_instance_;
class NotifyFriendRemove;
struct NotifyFriendRemoveDefaultTypeInternal;
extern NotifyFriendRemoveDefaultTypeInternal _NotifyFriendRemove_default_instance_;
class NotifyMessage;
struct NotifyMessageDefaultTypeInternal;
extern NotifyMessageDefaultTypeInternal _NotifyMessage_default_instance_;
class NotifyNewChatSession;
struct NotifyNewChatSessionDefaultTypeInternal;
extern NotifyNewChatSessionDefaultTypeInternal _NotifyNewChatSession_default_instance_;
class NotifyNewMessage;
struct NotifyNewMessageDefaultTypeInternal;
extern NotifyNewMessageDefaultTypeInternal _NotifyNewMessage_default_instance_;
}  // namespace chat_ns
PROTOBUF_NAMESPACE_OPEN
template<> ::chat_ns::NotifyFriendAddApply* Arena::CreateMaybeMessage<::chat_ns::NotifyFriendAddApply>(Arena*);
template<> ::chat_ns::NotifyFriendAddProcess* Arena::CreateMaybeMessage<::chat_ns::NotifyFriendAddProcess>(Arena*);
template<> ::chat_ns::NotifyFriendRemove* Arena::CreateMaybeMessage<::chat_ns::NotifyFriendRemove>(Arena*);
template<> ::chat_ns::NotifyMessage* Arena::CreateMaybeMessage<::chat_ns::NotifyMessage>(Arena*);
template<> ::chat_ns::NotifyNewChatSession* Arena::CreateMaybeMessage<::chat_ns::NotifyNewChatSession>(Arena*);
template<> ::chat_ns::NotifyNewMessage* Arena::CreateMaybeMessage<::chat_ns::NotifyNewMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace chat_ns {

enum NotifyType : int {
  FRIEND_ADD_APPLY_NOTIFY = 0,
  FRIEND_ADD_PROCESS_NOTIFY = 1,
  CHAT_SESSION_CREATE_NOTIFY = 2,
  CHAT_MESSAGE_NOTIFY = 3,
  FRIEND_REMOVE_NOTIFY = 4,
  NotifyType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  NotifyType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool NotifyType_IsValid(int value);
constexpr NotifyType NotifyType_MIN = FRIEND_ADD_APPLY_NOTIFY;
constexpr NotifyType NotifyType_MAX = FRIEND_REMOVE_NOTIFY;
constexpr int NotifyType_ARRAYSIZE = NotifyType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* NotifyType_descriptor();
template<typename T>
inline const std::string& NotifyType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, NotifyType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function NotifyType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    NotifyType_descriptor(), enum_t_value);
}
inline bool NotifyType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, NotifyType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<NotifyType>(
    NotifyType_descriptor(), name, value);
}
// ===================================================================

class NotifyFriendAddApply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chat_ns.NotifyFriendAddApply) */ {
 public:
  inline NotifyFriendAddApply() : NotifyFriendAddApply(nullptr) {}
  ~NotifyFriendAddApply() override;
  explicit PROTOBUF_CONSTEXPR NotifyFriendAddApply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NotifyFriendAddApply(const NotifyFriendAddApply& from);
  NotifyFriendAddApply(NotifyFriendAddApply&& from) noexcept
    : NotifyFriendAddApply() {
    *this = ::std::move(from);
  }

  inline NotifyFriendAddApply& operator=(const NotifyFriendAddApply& from) {
    CopyFrom(from);
    return *this;
  }
  inline NotifyFriendAddApply& operator=(NotifyFriendAddApply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NotifyFriendAddApply& default_instance() {
    return *internal_default_instance();
  }
  static inline const NotifyFriendAddApply* internal_default_instance() {
    return reinterpret_cast<const NotifyFriendAddApply*>(
               &_NotifyFriendAddApply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(NotifyFriendAddApply& a, NotifyFriendAddApply& b) {
    a.Swap(&b);
  }
  inline void Swap(NotifyFriendAddApply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NotifyFriendAddApply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NotifyFriendAddApply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NotifyFriendAddApply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const NotifyFriendAddApply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const NotifyFriendAddApply& from) {
    NotifyFriendAddApply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NotifyFriendAddApply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chat_ns.NotifyFriendAddApply";
  }
  protected:
  explicit NotifyFriendAddApply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserInfoFieldNumber = 1,
  };
  // .chat_ns.UserInfo user_info = 1;
  bool has_user_info() const;
  private:
  bool _internal_has_user_info() const;
  public:
  void clear_user_info();
  const ::chat_ns::UserInfo& user_info() const;
  PROTOBUF_NODISCARD ::chat_ns::UserInfo* release_user_info();
  ::chat_ns::UserInfo* mutable_user_info();
  void set_allocated_user_info(::chat_ns::UserInfo* user_info);
  private:
  const ::chat_ns::UserInfo& _internal_user_info() const;
  ::chat_ns::UserInfo* _internal_mutable_user_info();
  public:
  void unsafe_arena_set_allocated_user_info(
      ::chat_ns::UserInfo* user_info);
  ::chat_ns::UserInfo* unsafe_arena_release_user_info();

  // @@protoc_insertion_point(class_scope:chat_ns.NotifyFriendAddApply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::chat_ns::UserInfo* user_info_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_notify_2eproto;
};
// -------------------------------------------------------------------

class NotifyFriendAddProcess final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chat_ns.NotifyFriendAddProcess) */ {
 public:
  inline NotifyFriendAddProcess() : NotifyFriendAddProcess(nullptr) {}
  ~NotifyFriendAddProcess() override;
  explicit PROTOBUF_CONSTEXPR NotifyFriendAddProcess(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NotifyFriendAddProcess(const NotifyFriendAddProcess& from);
  NotifyFriendAddProcess(NotifyFriendAddProcess&& from) noexcept
    : NotifyFriendAddProcess() {
    *this = ::std::move(from);
  }

  inline NotifyFriendAddProcess& operator=(const NotifyFriendAddProcess& from) {
    CopyFrom(from);
    return *this;
  }
  inline NotifyFriendAddProcess& operator=(NotifyFriendAddProcess&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NotifyFriendAddProcess& default_instance() {
    return *internal_default_instance();
  }
  static inline const NotifyFriendAddProcess* internal_default_instance() {
    return reinterpret_cast<const NotifyFriendAddProcess*>(
               &_NotifyFriendAddProcess_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(NotifyFriendAddProcess& a, NotifyFriendAddProcess& b) {
    a.Swap(&b);
  }
  inline void Swap(NotifyFriendAddProcess* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NotifyFriendAddProcess* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NotifyFriendAddProcess* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NotifyFriendAddProcess>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const NotifyFriendAddProcess& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const NotifyFriendAddProcess& from) {
    NotifyFriendAddProcess::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NotifyFriendAddProcess* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chat_ns.NotifyFriendAddProcess";
  }
  protected:
  explicit NotifyFriendAddProcess(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserInfoFieldNumber = 2,
    kAgreeFieldNumber = 1,
  };
  // .chat_ns.UserInfo user_info = 2;
  bool has_user_info() const;
  private:
  bool _internal_has_user_info() const;
  public:
  void clear_user_info();
  const ::chat_ns::UserInfo& user_info() const;
  PROTOBUF_NODISCARD ::chat_ns::UserInfo* release_user_info();
  ::chat_ns::UserInfo* mutable_user_info();
  void set_allocated_user_info(::chat_ns::UserInfo* user_info);
  private:
  const ::chat_ns::UserInfo& _internal_user_info() const;
  ::chat_ns::UserInfo* _internal_mutable_user_info();
  public:
  void unsafe_arena_set_allocated_user_info(
      ::chat_ns::UserInfo* user_info);
  ::chat_ns::UserInfo* unsafe_arena_release_user_info();

  // bool agree = 1;
  void clear_agree();
  bool agree() const;
  void set_agree(bool value);
  private:
  bool _internal_agree() const;
  void _internal_set_agree(bool value);
  public:

  // @@protoc_insertion_point(class_scope:chat_ns.NotifyFriendAddProcess)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::chat_ns::UserInfo* user_info_;
    bool agree_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_notify_2eproto;
};
// -------------------------------------------------------------------

class NotifyFriendRemove final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chat_ns.NotifyFriendRemove) */ {
 public:
  inline NotifyFriendRemove() : NotifyFriendRemove(nullptr) {}
  ~NotifyFriendRemove() override;
  explicit PROTOBUF_CONSTEXPR NotifyFriendRemove(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NotifyFriendRemove(const NotifyFriendRemove& from);
  NotifyFriendRemove(NotifyFriendRemove&& from) noexcept
    : NotifyFriendRemove() {
    *this = ::std::move(from);
  }

  inline NotifyFriendRemove& operator=(const NotifyFriendRemove& from) {
    CopyFrom(from);
    return *this;
  }
  inline NotifyFriendRemove& operator=(NotifyFriendRemove&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NotifyFriendRemove& default_instance() {
    return *internal_default_instance();
  }
  static inline const NotifyFriendRemove* internal_default_instance() {
    return reinterpret_cast<const NotifyFriendRemove*>(
               &_NotifyFriendRemove_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(NotifyFriendRemove& a, NotifyFriendRemove& b) {
    a.Swap(&b);
  }
  inline void Swap(NotifyFriendRemove* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NotifyFriendRemove* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NotifyFriendRemove* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NotifyFriendRemove>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const NotifyFriendRemove& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const NotifyFriendRemove& from) {
    NotifyFriendRemove::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NotifyFriendRemove* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chat_ns.NotifyFriendRemove";
  }
  protected:
  explicit NotifyFriendRemove(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserIdFieldNumber = 1,
  };
  // string user_id = 1;
  void clear_user_id();
  const std::string& user_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_user_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_user_id();
  PROTOBUF_NODISCARD std::string* release_user_id();
  void set_allocated_user_id(std::string* user_id);
  private:
  const std::string& _internal_user_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_user_id(const std::string& value);
  std::string* _internal_mutable_user_id();
  public:

  // @@protoc_insertion_point(class_scope:chat_ns.NotifyFriendRemove)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_notify_2eproto;
};
// -------------------------------------------------------------------

class NotifyNewChatSession final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chat_ns.NotifyNewChatSession) */ {
 public:
  inline NotifyNewChatSession() : NotifyNewChatSession(nullptr) {}
  ~NotifyNewChatSession() override;
  explicit PROTOBUF_CONSTEXPR NotifyNewChatSession(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NotifyNewChatSession(const NotifyNewChatSession& from);
  NotifyNewChatSession(NotifyNewChatSession&& from) noexcept
    : NotifyNewChatSession() {
    *this = ::std::move(from);
  }

  inline NotifyNewChatSession& operator=(const NotifyNewChatSession& from) {
    CopyFrom(from);
    return *this;
  }
  inline NotifyNewChatSession& operator=(NotifyNewChatSession&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NotifyNewChatSession& default_instance() {
    return *internal_default_instance();
  }
  static inline const NotifyNewChatSession* internal_default_instance() {
    return reinterpret_cast<const NotifyNewChatSession*>(
               &_NotifyNewChatSession_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(NotifyNewChatSession& a, NotifyNewChatSession& b) {
    a.Swap(&b);
  }
  inline void Swap(NotifyNewChatSession* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NotifyNewChatSession* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NotifyNewChatSession* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NotifyNewChatSession>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const NotifyNewChatSession& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const NotifyNewChatSession& from) {
    NotifyNewChatSession::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NotifyNewChatSession* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chat_ns.NotifyNewChatSession";
  }
  protected:
  explicit NotifyNewChatSession(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kChatSessionInfoFieldNumber = 1,
  };
  // .chat_ns.ChatSessionInfo chat_session_info = 1;
  bool has_chat_session_info() const;
  private:
  bool _internal_has_chat_session_info() const;
  public:
  void clear_chat_session_info();
  const ::chat_ns::ChatSessionInfo& chat_session_info() const;
  PROTOBUF_NODISCARD ::chat_ns::ChatSessionInfo* release_chat_session_info();
  ::chat_ns::ChatSessionInfo* mutable_chat_session_info();
  void set_allocated_chat_session_info(::chat_ns::ChatSessionInfo* chat_session_info);
  private:
  const ::chat_ns::ChatSessionInfo& _internal_chat_session_info() const;
  ::chat_ns::ChatSessionInfo* _internal_mutable_chat_session_info();
  public:
  void unsafe_arena_set_allocated_chat_session_info(
      ::chat_ns::ChatSessionInfo* chat_session_info);
  ::chat_ns::ChatSessionInfo* unsafe_arena_release_chat_session_info();

  // @@protoc_insertion_point(class_scope:chat_ns.NotifyNewChatSession)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::chat_ns::ChatSessionInfo* chat_session_info_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_notify_2eproto;
};
// -------------------------------------------------------------------

class NotifyNewMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chat_ns.NotifyNewMessage) */ {
 public:
  inline NotifyNewMessage() : NotifyNewMessage(nullptr) {}
  ~NotifyNewMessage() override;
  explicit PROTOBUF_CONSTEXPR NotifyNewMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NotifyNewMessage(const NotifyNewMessage& from);
  NotifyNewMessage(NotifyNewMessage&& from) noexcept
    : NotifyNewMessage() {
    *this = ::std::move(from);
  }

  inline NotifyNewMessage& operator=(const NotifyNewMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline NotifyNewMessage& operator=(NotifyNewMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NotifyNewMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const NotifyNewMessage* internal_default_instance() {
    return reinterpret_cast<const NotifyNewMessage*>(
               &_NotifyNewMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(NotifyNewMessage& a, NotifyNewMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(NotifyNewMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NotifyNewMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NotifyNewMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NotifyNewMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const NotifyNewMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const NotifyNewMessage& from) {
    NotifyNewMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NotifyNewMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chat_ns.NotifyNewMessage";
  }
  protected:
  explicit NotifyNewMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageInfoFieldNumber = 1,
  };
  // .chat_ns.MessageInfo message_info = 1;
  bool has_message_info() const;
  private:
  bool _internal_has_message_info() const;
  public:
  void clear_message_info();
  const ::chat_ns::MessageInfo& message_info() const;
  PROTOBUF_NODISCARD ::chat_ns::MessageInfo* release_message_info();
  ::chat_ns::MessageInfo* mutable_message_info();
  void set_allocated_message_info(::chat_ns::MessageInfo* message_info);
  private:
  const ::chat_ns::MessageInfo& _internal_message_info() const;
  ::chat_ns::MessageInfo* _internal_mutable_message_info();
  public:
  void unsafe_arena_set_allocated_message_info(
      ::chat_ns::MessageInfo* message_info);
  ::chat_ns::MessageInfo* unsafe_arena_release_message_info();

  // @@protoc_insertion_point(class_scope:chat_ns.NotifyNewMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::chat_ns::MessageInfo* message_info_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_notify_2eproto;
};
// -------------------------------------------------------------------

class NotifyMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chat_ns.NotifyMessage) */ {
 public:
  inline NotifyMessage() : NotifyMessage(nullptr) {}
  ~NotifyMessage() override;
  explicit PROTOBUF_CONSTEXPR NotifyMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NotifyMessage(const NotifyMessage& from);
  NotifyMessage(NotifyMessage&& from) noexcept
    : NotifyMessage() {
    *this = ::std::move(from);
  }

  inline NotifyMessage& operator=(const NotifyMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline NotifyMessage& operator=(NotifyMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NotifyMessage& default_instance() {
    return *internal_default_instance();
  }
  enum NotifyRemarksCase {
    kFriendAddApply = 3,
    kFriendProcessResult = 4,
    kFriendRemove = 7,
    kNewChatSessionInfo = 5,
    kNewMessageInfo = 6,
    NOTIFY_REMARKS_NOT_SET = 0,
  };

  static inline const NotifyMessage* internal_default_instance() {
    return reinterpret_cast<const NotifyMessage*>(
               &_NotifyMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(NotifyMessage& a, NotifyMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(NotifyMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NotifyMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NotifyMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NotifyMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const NotifyMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const NotifyMessage& from) {
    NotifyMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NotifyMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chat_ns.NotifyMessage";
  }
  protected:
  explicit NotifyMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNotifyEventIdFieldNumber = 1,
    kNotifyTypeFieldNumber = 2,
    kFriendAddApplyFieldNumber = 3,
    kFriendProcessResultFieldNumber = 4,
    kFriendRemoveFieldNumber = 7,
    kNewChatSessionInfoFieldNumber = 5,
    kNewMessageInfoFieldNumber = 6,
  };
  // optional string notify_event_id = 1;
  bool has_notify_event_id() const;
  private:
  bool _internal_has_notify_event_id() const;
  public:
  void clear_notify_event_id();
  const std::string& notify_event_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_notify_event_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_notify_event_id();
  PROTOBUF_NODISCARD std::string* release_notify_event_id();
  void set_allocated_notify_event_id(std::string* notify_event_id);
  private:
  const std::string& _internal_notify_event_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_notify_event_id(const std::string& value);
  std::string* _internal_mutable_notify_event_id();
  public:

  // .chat_ns.NotifyType notify_type = 2;
  void clear_notify_type();
  ::chat_ns::NotifyType notify_type() const;
  void set_notify_type(::chat_ns::NotifyType value);
  private:
  ::chat_ns::NotifyType _internal_notify_type() const;
  void _internal_set_notify_type(::chat_ns::NotifyType value);
  public:

  // .chat_ns.NotifyFriendAddApply friend_add_apply = 3;
  bool has_friend_add_apply() const;
  private:
  bool _internal_has_friend_add_apply() const;
  public:
  void clear_friend_add_apply();
  const ::chat_ns::NotifyFriendAddApply& friend_add_apply() const;
  PROTOBUF_NODISCARD ::chat_ns::NotifyFriendAddApply* release_friend_add_apply();
  ::chat_ns::NotifyFriendAddApply* mutable_friend_add_apply();
  void set_allocated_friend_add_apply(::chat_ns::NotifyFriendAddApply* friend_add_apply);
  private:
  const ::chat_ns::NotifyFriendAddApply& _internal_friend_add_apply() const;
  ::chat_ns::NotifyFriendAddApply* _internal_mutable_friend_add_apply();
  public:
  void unsafe_arena_set_allocated_friend_add_apply(
      ::chat_ns::NotifyFriendAddApply* friend_add_apply);
  ::chat_ns::NotifyFriendAddApply* unsafe_arena_release_friend_add_apply();

  // .chat_ns.NotifyFriendAddProcess friend_process_result = 4;
  bool has_friend_process_result() const;
  private:
  bool _internal_has_friend_process_result() const;
  public:
  void clear_friend_process_result();
  const ::chat_ns::NotifyFriendAddProcess& friend_process_result() const;
  PROTOBUF_NODISCARD ::chat_ns::NotifyFriendAddProcess* release_friend_process_result();
  ::chat_ns::NotifyFriendAddProcess* mutable_friend_process_result();
  void set_allocated_friend_process_result(::chat_ns::NotifyFriendAddProcess* friend_process_result);
  private:
  const ::chat_ns::NotifyFriendAddProcess& _internal_friend_process_result() const;
  ::chat_ns::NotifyFriendAddProcess* _internal_mutable_friend_process_result();
  public:
  void unsafe_arena_set_allocated_friend_process_result(
      ::chat_ns::NotifyFriendAddProcess* friend_process_result);
  ::chat_ns::NotifyFriendAddProcess* unsafe_arena_release_friend_process_result();

  // .chat_ns.NotifyFriendRemove friend_remove = 7;
  bool has_friend_remove() const;
  private:
  bool _internal_has_friend_remove() const;
  public:
  void clear_friend_remove();
  const ::chat_ns::NotifyFriendRemove& friend_remove() const;
  PROTOBUF_NODISCARD ::chat_ns::NotifyFriendRemove* release_friend_remove();
  ::chat_ns::NotifyFriendRemove* mutable_friend_remove();
  void set_allocated_friend_remove(::chat_ns::NotifyFriendRemove* friend_remove);
  private:
  const ::chat_ns::NotifyFriendRemove& _internal_friend_remove() const;
  ::chat_ns::NotifyFriendRemove* _internal_mutable_friend_remove();
  public:
  void unsafe_arena_set_allocated_friend_remove(
      ::chat_ns::NotifyFriendRemove* friend_remove);
  ::chat_ns::NotifyFriendRemove* unsafe_arena_release_friend_remove();

  // .chat_ns.NotifyNewChatSession new_chat_session_info = 5;
  bool has_new_chat_session_info() const;
  private:
  bool _internal_has_new_chat_session_info() const;
  public:
  void clear_new_chat_session_info();
  const ::chat_ns::NotifyNewChatSession& new_chat_session_info() const;
  PROTOBUF_NODISCARD ::chat_ns::NotifyNewChatSession* release_new_chat_session_info();
  ::chat_ns::NotifyNewChatSession* mutable_new_chat_session_info();
  void set_allocated_new_chat_session_info(::chat_ns::NotifyNewChatSession* new_chat_session_info);
  private:
  const ::chat_ns::NotifyNewChatSession& _internal_new_chat_session_info() const;
  ::chat_ns::NotifyNewChatSession* _internal_mutable_new_chat_session_info();
  public:
  void unsafe_arena_set_allocated_new_chat_session_info(
      ::chat_ns::NotifyNewChatSession* new_chat_session_info);
  ::chat_ns::NotifyNewChatSession* unsafe_arena_release_new_chat_session_info();

  // .chat_ns.NotifyNewMessage new_message_info = 6;
  bool has_new_message_info() const;
  private:
  bool _internal_has_new_message_info() const;
  public:
  void clear_new_message_info();
  const ::chat_ns::NotifyNewMessage& new_message_info() const;
  PROTOBUF_NODISCARD ::chat_ns::NotifyNewMessage* release_new_message_info();
  ::chat_ns::NotifyNewMessage* mutable_new_message_info();
  void set_allocated_new_message_info(::chat_ns::NotifyNewMessage* new_message_info);
  private:
  const ::chat_ns::NotifyNewMessage& _internal_new_message_info() const;
  ::chat_ns::NotifyNewMessage* _internal_mutable_new_message_info();
  public:
  void unsafe_arena_set_allocated_new_message_info(
      ::chat_ns::NotifyNewMessage* new_message_info);
  ::chat_ns::NotifyNewMessage* unsafe_arena_release_new_message_info();

  void clear_notify_remarks();
  NotifyRemarksCase notify_remarks_case() const;
  // @@protoc_insertion_point(class_scope:chat_ns.NotifyMessage)
 private:
  class _Internal;
  void set_has_friend_add_apply();
  void set_has_friend_process_result();
  void set_has_friend_remove();
  void set_has_new_chat_session_info();
  void set_has_new_message_info();

  inline bool has_notify_remarks() const;
  inline void clear_has_notify_remarks();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr notify_event_id_;
    int notify_type_;
    union NotifyRemarksUnion {
      constexpr NotifyRemarksUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::chat_ns::NotifyFriendAddApply* friend_add_apply_;
      ::chat_ns::NotifyFriendAddProcess* friend_process_result_;
      ::chat_ns::NotifyFriendRemove* friend_remove_;
      ::chat_ns::NotifyNewChatSession* new_chat_session_info_;
      ::chat_ns::NotifyNewMessage* new_message_info_;
    } notify_remarks_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_notify_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NotifyFriendAddApply

// .chat_ns.UserInfo user_info = 1;
inline bool NotifyFriendAddApply::_internal_has_user_info() const {
  return this != internal_default_instance() && _impl_.user_info_ != nullptr;
}
inline bool NotifyFriendAddApply::has_user_info() const {
  return _internal_has_user_info();
}
inline const ::chat_ns::UserInfo& NotifyFriendAddApply::_internal_user_info() const {
  const ::chat_ns::UserInfo* p = _impl_.user_info_;
  return p != nullptr ? *p : reinterpret_cast<const ::chat_ns::UserInfo&>(
      ::chat_ns::_UserInfo_default_instance_);
}
inline const ::chat_ns::UserInfo& NotifyFriendAddApply::user_info() const {
  // @@protoc_insertion_point(field_get:chat_ns.NotifyFriendAddApply.user_info)
  return _internal_user_info();
}
inline void NotifyFriendAddApply::unsafe_arena_set_allocated_user_info(
    ::chat_ns::UserInfo* user_info) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.user_info_);
  }
  _impl_.user_info_ = user_info;
  if (user_info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:chat_ns.NotifyFriendAddApply.user_info)
}
inline ::chat_ns::UserInfo* NotifyFriendAddApply::release_user_info() {
  
  ::chat_ns::UserInfo* temp = _impl_.user_info_;
  _impl_.user_info_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::chat_ns::UserInfo* NotifyFriendAddApply::unsafe_arena_release_user_info() {
  // @@protoc_insertion_point(field_release:chat_ns.NotifyFriendAddApply.user_info)
  
  ::chat_ns::UserInfo* temp = _impl_.user_info_;
  _impl_.user_info_ = nullptr;
  return temp;
}
inline ::chat_ns::UserInfo* NotifyFriendAddApply::_internal_mutable_user_info() {
  
  if (_impl_.user_info_ == nullptr) {
    auto* p = CreateMaybeMessage<::chat_ns::UserInfo>(GetArenaForAllocation());
    _impl_.user_info_ = p;
  }
  return _impl_.user_info_;
}
inline ::chat_ns::UserInfo* NotifyFriendAddApply::mutable_user_info() {
  ::chat_ns::UserInfo* _msg = _internal_mutable_user_info();
  // @@protoc_insertion_point(field_mutable:chat_ns.NotifyFriendAddApply.user_info)
  return _msg;
}
inline void NotifyFriendAddApply::set_allocated_user_info(::chat_ns::UserInfo* user_info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.user_info_);
  }
  if (user_info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(user_info));
    if (message_arena != submessage_arena) {
      user_info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, user_info, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.user_info_ = user_info;
  // @@protoc_insertion_point(field_set_allocated:chat_ns.NotifyFriendAddApply.user_info)
}

// -------------------------------------------------------------------

// NotifyFriendAddProcess

// bool agree = 1;
inline void NotifyFriendAddProcess::clear_agree() {
  _impl_.agree_ = false;
}
inline bool NotifyFriendAddProcess::_internal_agree() const {
  return _impl_.agree_;
}
inline bool NotifyFriendAddProcess::agree() const {
  // @@protoc_insertion_point(field_get:chat_ns.NotifyFriendAddProcess.agree)
  return _internal_agree();
}
inline void NotifyFriendAddProcess::_internal_set_agree(bool value) {
  
  _impl_.agree_ = value;
}
inline void NotifyFriendAddProcess::set_agree(bool value) {
  _internal_set_agree(value);
  // @@protoc_insertion_point(field_set:chat_ns.NotifyFriendAddProcess.agree)
}

// .chat_ns.UserInfo user_info = 2;
inline bool NotifyFriendAddProcess::_internal_has_user_info() const {
  return this != internal_default_instance() && _impl_.user_info_ != nullptr;
}
inline bool NotifyFriendAddProcess::has_user_info() const {
  return _internal_has_user_info();
}
inline const ::chat_ns::UserInfo& NotifyFriendAddProcess::_internal_user_info() const {
  const ::chat_ns::UserInfo* p = _impl_.user_info_;
  return p != nullptr ? *p : reinterpret_cast<const ::chat_ns::UserInfo&>(
      ::chat_ns::_UserInfo_default_instance_);
}
inline const ::chat_ns::UserInfo& NotifyFriendAddProcess::user_info() const {
  // @@protoc_insertion_point(field_get:chat_ns.NotifyFriendAddProcess.user_info)
  return _internal_user_info();
}
inline void NotifyFriendAddProcess::unsafe_arena_set_allocated_user_info(
    ::chat_ns::UserInfo* user_info) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.user_info_);
  }
  _impl_.user_info_ = user_info;
  if (user_info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:chat_ns.NotifyFriendAddProcess.user_info)
}
inline ::chat_ns::UserInfo* NotifyFriendAddProcess::release_user_info() {
  
  ::chat_ns::UserInfo* temp = _impl_.user_info_;
  _impl_.user_info_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::chat_ns::UserInfo* NotifyFriendAddProcess::unsafe_arena_release_user_info() {
  // @@protoc_insertion_point(field_release:chat_ns.NotifyFriendAddProcess.user_info)
  
  ::chat_ns::UserInfo* temp = _impl_.user_info_;
  _impl_.user_info_ = nullptr;
  return temp;
}
inline ::chat_ns::UserInfo* NotifyFriendAddProcess::_internal_mutable_user_info() {
  
  if (_impl_.user_info_ == nullptr) {
    auto* p = CreateMaybeMessage<::chat_ns::UserInfo>(GetArenaForAllocation());
    _impl_.user_info_ = p;
  }
  return _impl_.user_info_;
}
inline ::chat_ns::UserInfo* NotifyFriendAddProcess::mutable_user_info() {
  ::chat_ns::UserInfo* _msg = _internal_mutable_user_info();
  // @@protoc_insertion_point(field_mutable:chat_ns.NotifyFriendAddProcess.user_info)
  return _msg;
}
inline void NotifyFriendAddProcess::set_allocated_user_info(::chat_ns::UserInfo* user_info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.user_info_);
  }
  if (user_info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(user_info));
    if (message_arena != submessage_arena) {
      user_info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, user_info, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.user_info_ = user_info;
  // @@protoc_insertion_point(field_set_allocated:chat_ns.NotifyFriendAddProcess.user_info)
}

// -------------------------------------------------------------------

// NotifyFriendRemove

// string user_id = 1;
inline void NotifyFriendRemove::clear_user_id() {
  _impl_.user_id_.ClearToEmpty();
}
inline const std::string& NotifyFriendRemove::user_id() const {
  // @@protoc_insertion_point(field_get:chat_ns.NotifyFriendRemove.user_id)
  return _internal_user_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void NotifyFriendRemove::set_user_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.user_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chat_ns.NotifyFriendRemove.user_id)
}
inline std::string* NotifyFriendRemove::mutable_user_id() {
  std::string* _s = _internal_mutable_user_id();
  // @@protoc_insertion_point(field_mutable:chat_ns.NotifyFriendRemove.user_id)
  return _s;
}
inline const std::string& NotifyFriendRemove::_internal_user_id() const {
  return _impl_.user_id_.Get();
}
inline void NotifyFriendRemove::_internal_set_user_id(const std::string& value) {
  
  _impl_.user_id_.Set(value, GetArenaForAllocation());
}
inline std::string* NotifyFriendRemove::_internal_mutable_user_id() {
  
  return _impl_.user_id_.Mutable(GetArenaForAllocation());
}
inline std::string* NotifyFriendRemove::release_user_id() {
  // @@protoc_insertion_point(field_release:chat_ns.NotifyFriendRemove.user_id)
  return _impl_.user_id_.Release();
}
inline void NotifyFriendRemove::set_allocated_user_id(std::string* user_id) {
  if (user_id != nullptr) {
    
  } else {
    
  }
  _impl_.user_id_.SetAllocated(user_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.user_id_.IsDefault()) {
    _impl_.user_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chat_ns.NotifyFriendRemove.user_id)
}

// -------------------------------------------------------------------

// NotifyNewChatSession

// .chat_ns.ChatSessionInfo chat_session_info = 1;
inline bool NotifyNewChatSession::_internal_has_chat_session_info() const {
  return this != internal_default_instance() && _impl_.chat_session_info_ != nullptr;
}
inline bool NotifyNewChatSession::has_chat_session_info() const {
  return _internal_has_chat_session_info();
}
inline const ::chat_ns::ChatSessionInfo& NotifyNewChatSession::_internal_chat_session_info() const {
  const ::chat_ns::ChatSessionInfo* p = _impl_.chat_session_info_;
  return p != nullptr ? *p : reinterpret_cast<const ::chat_ns::ChatSessionInfo&>(
      ::chat_ns::_ChatSessionInfo_default_instance_);
}
inline const ::chat_ns::ChatSessionInfo& NotifyNewChatSession::chat_session_info() const {
  // @@protoc_insertion_point(field_get:chat_ns.NotifyNewChatSession.chat_session_info)
  return _internal_chat_session_info();
}
inline void NotifyNewChatSession::unsafe_arena_set_allocated_chat_session_info(
    ::chat_ns::ChatSessionInfo* chat_session_info) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.chat_session_info_);
  }
  _impl_.chat_session_info_ = chat_session_info;
  if (chat_session_info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:chat_ns.NotifyNewChatSession.chat_session_info)
}
inline ::chat_ns::ChatSessionInfo* NotifyNewChatSession::release_chat_session_info() {
  
  ::chat_ns::ChatSessionInfo* temp = _impl_.chat_session_info_;
  _impl_.chat_session_info_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::chat_ns::ChatSessionInfo* NotifyNewChatSession::unsafe_arena_release_chat_session_info() {
  // @@protoc_insertion_point(field_release:chat_ns.NotifyNewChatSession.chat_session_info)
  
  ::chat_ns::ChatSessionInfo* temp = _impl_.chat_session_info_;
  _impl_.chat_session_info_ = nullptr;
  return temp;
}
inline ::chat_ns::ChatSessionInfo* NotifyNewChatSession::_internal_mutable_chat_session_info() {
  
  if (_impl_.chat_session_info_ == nullptr) {
    auto* p = CreateMaybeMessage<::chat_ns::ChatSessionInfo>(GetArenaForAllocation());
    _impl_.chat_session_info_ = p;
  }
  return _impl_.chat_session_info_;
}
inline ::chat_ns::ChatSessionInfo* NotifyNewChatSession::mutable_chat_session_info() {
  ::chat_ns::ChatSessionInfo* _msg = _internal_mutable_chat_session_info();
  // @@protoc_insertion_point(field_mutable:chat_ns.NotifyNewChatSession.chat_session_info)
  return _msg;
}
inline void NotifyNewChatSession::set_allocated_chat_session_info(::chat_ns::ChatSessionInfo* chat_session_info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.chat_session_info_);
  }
  if (chat_session_info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(chat_session_info));
    if (message_arena != submessage_arena) {
      chat_session_info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, chat_session_info, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.chat_session_info_ = chat_session_info;
  // @@protoc_insertion_point(field_set_allocated:chat_ns.NotifyNewChatSession.chat_session_info)
}

// -------------------------------------------------------------------

// NotifyNewMessage

// .chat_ns.MessageInfo message_info = 1;
inline bool NotifyNewMessage::_internal_has_message_info() const {
  return this != internal_default_instance() && _impl_.message_info_ != nullptr;
}
inline bool NotifyNewMessage::has_message_info() const {
  return _internal_has_message_info();
}
inline const ::chat_ns::MessageInfo& NotifyNewMessage::_internal_message_info() const {
  const ::chat_ns::MessageInfo* p = _impl_.message_info_;
  return p != nullptr ? *p : reinterpret_cast<const ::chat_ns::MessageInfo&>(
      ::chat_ns::_MessageInfo_default_instance_);
}
inline const ::chat_ns::MessageInfo& NotifyNewMessage::message_info() const {
  // @@protoc_insertion_point(field_get:chat_ns.NotifyNewMessage.message_info)
  return _internal_message_info();
}
inline void NotifyNewMessage::unsafe_arena_set_allocated_message_info(
    ::chat_ns::MessageInfo* message_info) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.message_info_);
  }
  _impl_.message_info_ = message_info;
  if (message_info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:chat_ns.NotifyNewMessage.message_info)
}
inline ::chat_ns::MessageInfo* NotifyNewMessage::release_message_info() {
  
  ::chat_ns::MessageInfo* temp = _impl_.message_info_;
  _impl_.message_info_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::chat_ns::MessageInfo* NotifyNewMessage::unsafe_arena_release_message_info() {
  // @@protoc_insertion_point(field_release:chat_ns.NotifyNewMessage.message_info)
  
  ::chat_ns::MessageInfo* temp = _impl_.message_info_;
  _impl_.message_info_ = nullptr;
  return temp;
}
inline ::chat_ns::MessageInfo* NotifyNewMessage::_internal_mutable_message_info() {
  
  if (_impl_.message_info_ == nullptr) {
    auto* p = CreateMaybeMessage<::chat_ns::MessageInfo>(GetArenaForAllocation());
    _impl_.message_info_ = p;
  }
  return _impl_.message_info_;
}
inline ::chat_ns::MessageInfo* NotifyNewMessage::mutable_message_info() {
  ::chat_ns::MessageInfo* _msg = _internal_mutable_message_info();
  // @@protoc_insertion_point(field_mutable:chat_ns.NotifyNewMessage.message_info)
  return _msg;
}
inline void NotifyNewMessage::set_allocated_message_info(::chat_ns::MessageInfo* message_info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.message_info_);
  }
  if (message_info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(message_info));
    if (message_arena != submessage_arena) {
      message_info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, message_info, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.message_info_ = message_info;
  // @@protoc_insertion_point(field_set_allocated:chat_ns.NotifyNewMessage.message_info)
}

// -------------------------------------------------------------------

// NotifyMessage

// optional string notify_event_id = 1;
inline bool NotifyMessage::_internal_has_notify_event_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool NotifyMessage::has_notify_event_id() const {
  return _internal_has_notify_event_id();
}
inline void NotifyMessage::clear_notify_event_id() {
  _impl_.notify_event_id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& NotifyMessage::notify_event_id() const {
  // @@protoc_insertion_point(field_get:chat_ns.NotifyMessage.notify_event_id)
  return _internal_notify_event_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void NotifyMessage::set_notify_event_id(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.notify_event_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chat_ns.NotifyMessage.notify_event_id)
}
inline std::string* NotifyMessage::mutable_notify_event_id() {
  std::string* _s = _internal_mutable_notify_event_id();
  // @@protoc_insertion_point(field_mutable:chat_ns.NotifyMessage.notify_event_id)
  return _s;
}
inline const std::string& NotifyMessage::_internal_notify_event_id() const {
  return _impl_.notify_event_id_.Get();
}
inline void NotifyMessage::_internal_set_notify_event_id(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.notify_event_id_.Set(value, GetArenaForAllocation());
}
inline std::string* NotifyMessage::_internal_mutable_notify_event_id() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.notify_event_id_.Mutable(GetArenaForAllocation());
}
inline std::string* NotifyMessage::release_notify_event_id() {
  // @@protoc_insertion_point(field_release:chat_ns.NotifyMessage.notify_event_id)
  if (!_internal_has_notify_event_id()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.notify_event_id_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.notify_event_id_.IsDefault()) {
    _impl_.notify_event_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void NotifyMessage::set_allocated_notify_event_id(std::string* notify_event_id) {
  if (notify_event_id != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.notify_event_id_.SetAllocated(notify_event_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.notify_event_id_.IsDefault()) {
    _impl_.notify_event_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chat_ns.NotifyMessage.notify_event_id)
}

// .chat_ns.NotifyType notify_type = 2;
inline void NotifyMessage::clear_notify_type() {
  _impl_.notify_type_ = 0;
}
inline ::chat_ns::NotifyType NotifyMessage::_internal_notify_type() const {
  return static_cast< ::chat_ns::NotifyType >(_impl_.notify_type_);
}
inline ::chat_ns::NotifyType NotifyMessage::notify_type() const {
  // @@protoc_insertion_point(field_get:chat_ns.NotifyMessage.notify_type)
  return _internal_notify_type();
}
inline void NotifyMessage::_internal_set_notify_type(::chat_ns::NotifyType value) {
  
  _impl_.notify_type_ = value;
}
inline void NotifyMessage::set_notify_type(::chat_ns::NotifyType value) {
  _internal_set_notify_type(value);
  // @@protoc_insertion_point(field_set:chat_ns.NotifyMessage.notify_type)
}

// .chat_ns.NotifyFriendAddApply friend_add_apply = 3;
inline bool NotifyMessage::_internal_has_friend_add_apply() const {
  return notify_remarks_case() == kFriendAddApply;
}
inline bool NotifyMessage::has_friend_add_apply() const {
  return _internal_has_friend_add_apply();
}
inline void NotifyMessage::set_has_friend_add_apply() {
  _impl_._oneof_case_[0] = kFriendAddApply;
}
inline void NotifyMessage::clear_friend_add_apply() {
  if (_internal_has_friend_add_apply()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.notify_remarks_.friend_add_apply_;
    }
    clear_has_notify_remarks();
  }
}
inline ::chat_ns::NotifyFriendAddApply* NotifyMessage::release_friend_add_apply() {
  // @@protoc_insertion_point(field_release:chat_ns.NotifyMessage.friend_add_apply)
  if (_internal_has_friend_add_apply()) {
    clear_has_notify_remarks();
    ::chat_ns::NotifyFriendAddApply* temp = _impl_.notify_remarks_.friend_add_apply_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.notify_remarks_.friend_add_apply_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::chat_ns::NotifyFriendAddApply& NotifyMessage::_internal_friend_add_apply() const {
  return _internal_has_friend_add_apply()
      ? *_impl_.notify_remarks_.friend_add_apply_
      : reinterpret_cast< ::chat_ns::NotifyFriendAddApply&>(::chat_ns::_NotifyFriendAddApply_default_instance_);
}
inline const ::chat_ns::NotifyFriendAddApply& NotifyMessage::friend_add_apply() const {
  // @@protoc_insertion_point(field_get:chat_ns.NotifyMessage.friend_add_apply)
  return _internal_friend_add_apply();
}
inline ::chat_ns::NotifyFriendAddApply* NotifyMessage::unsafe_arena_release_friend_add_apply() {
  // @@protoc_insertion_point(field_unsafe_arena_release:chat_ns.NotifyMessage.friend_add_apply)
  if (_internal_has_friend_add_apply()) {
    clear_has_notify_remarks();
    ::chat_ns::NotifyFriendAddApply* temp = _impl_.notify_remarks_.friend_add_apply_;
    _impl_.notify_remarks_.friend_add_apply_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void NotifyMessage::unsafe_arena_set_allocated_friend_add_apply(::chat_ns::NotifyFriendAddApply* friend_add_apply) {
  clear_notify_remarks();
  if (friend_add_apply) {
    set_has_friend_add_apply();
    _impl_.notify_remarks_.friend_add_apply_ = friend_add_apply;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:chat_ns.NotifyMessage.friend_add_apply)
}
inline ::chat_ns::NotifyFriendAddApply* NotifyMessage::_internal_mutable_friend_add_apply() {
  if (!_internal_has_friend_add_apply()) {
    clear_notify_remarks();
    set_has_friend_add_apply();
    _impl_.notify_remarks_.friend_add_apply_ = CreateMaybeMessage< ::chat_ns::NotifyFriendAddApply >(GetArenaForAllocation());
  }
  return _impl_.notify_remarks_.friend_add_apply_;
}
inline ::chat_ns::NotifyFriendAddApply* NotifyMessage::mutable_friend_add_apply() {
  ::chat_ns::NotifyFriendAddApply* _msg = _internal_mutable_friend_add_apply();
  // @@protoc_insertion_point(field_mutable:chat_ns.NotifyMessage.friend_add_apply)
  return _msg;
}

// .chat_ns.NotifyFriendAddProcess friend_process_result = 4;
inline bool NotifyMessage::_internal_has_friend_process_result() const {
  return notify_remarks_case() == kFriendProcessResult;
}
inline bool NotifyMessage::has_friend_process_result() const {
  return _internal_has_friend_process_result();
}
inline void NotifyMessage::set_has_friend_process_result() {
  _impl_._oneof_case_[0] = kFriendProcessResult;
}
inline void NotifyMessage::clear_friend_process_result() {
  if (_internal_has_friend_process_result()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.notify_remarks_.friend_process_result_;
    }
    clear_has_notify_remarks();
  }
}
inline ::chat_ns::NotifyFriendAddProcess* NotifyMessage::release_friend_process_result() {
  // @@protoc_insertion_point(field_release:chat_ns.NotifyMessage.friend_process_result)
  if (_internal_has_friend_process_result()) {
    clear_has_notify_remarks();
    ::chat_ns::NotifyFriendAddProcess* temp = _impl_.notify_remarks_.friend_process_result_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.notify_remarks_.friend_process_result_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::chat_ns::NotifyFriendAddProcess& NotifyMessage::_internal_friend_process_result() const {
  return _internal_has_friend_process_result()
      ? *_impl_.notify_remarks_.friend_process_result_
      : reinterpret_cast< ::chat_ns::NotifyFriendAddProcess&>(::chat_ns::_NotifyFriendAddProcess_default_instance_);
}
inline const ::chat_ns::NotifyFriendAddProcess& NotifyMessage::friend_process_result() const {
  // @@protoc_insertion_point(field_get:chat_ns.NotifyMessage.friend_process_result)
  return _internal_friend_process_result();
}
inline ::chat_ns::NotifyFriendAddProcess* NotifyMessage::unsafe_arena_release_friend_process_result() {
  // @@protoc_insertion_point(field_unsafe_arena_release:chat_ns.NotifyMessage.friend_process_result)
  if (_internal_has_friend_process_result()) {
    clear_has_notify_remarks();
    ::chat_ns::NotifyFriendAddProcess* temp = _impl_.notify_remarks_.friend_process_result_;
    _impl_.notify_remarks_.friend_process_result_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void NotifyMessage::unsafe_arena_set_allocated_friend_process_result(::chat_ns::NotifyFriendAddProcess* friend_process_result) {
  clear_notify_remarks();
  if (friend_process_result) {
    set_has_friend_process_result();
    _impl_.notify_remarks_.friend_process_result_ = friend_process_result;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:chat_ns.NotifyMessage.friend_process_result)
}
inline ::chat_ns::NotifyFriendAddProcess* NotifyMessage::_internal_mutable_friend_process_result() {
  if (!_internal_has_friend_process_result()) {
    clear_notify_remarks();
    set_has_friend_process_result();
    _impl_.notify_remarks_.friend_process_result_ = CreateMaybeMessage< ::chat_ns::NotifyFriendAddProcess >(GetArenaForAllocation());
  }
  return _impl_.notify_remarks_.friend_process_result_;
}
inline ::chat_ns::NotifyFriendAddProcess* NotifyMessage::mutable_friend_process_result() {
  ::chat_ns::NotifyFriendAddProcess* _msg = _internal_mutable_friend_process_result();
  // @@protoc_insertion_point(field_mutable:chat_ns.NotifyMessage.friend_process_result)
  return _msg;
}

// .chat_ns.NotifyFriendRemove friend_remove = 7;
inline bool NotifyMessage::_internal_has_friend_remove() const {
  return notify_remarks_case() == kFriendRemove;
}
inline bool NotifyMessage::has_friend_remove() const {
  return _internal_has_friend_remove();
}
inline void NotifyMessage::set_has_friend_remove() {
  _impl_._oneof_case_[0] = kFriendRemove;
}
inline void NotifyMessage::clear_friend_remove() {
  if (_internal_has_friend_remove()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.notify_remarks_.friend_remove_;
    }
    clear_has_notify_remarks();
  }
}
inline ::chat_ns::NotifyFriendRemove* NotifyMessage::release_friend_remove() {
  // @@protoc_insertion_point(field_release:chat_ns.NotifyMessage.friend_remove)
  if (_internal_has_friend_remove()) {
    clear_has_notify_remarks();
    ::chat_ns::NotifyFriendRemove* temp = _impl_.notify_remarks_.friend_remove_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.notify_remarks_.friend_remove_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::chat_ns::NotifyFriendRemove& NotifyMessage::_internal_friend_remove() const {
  return _internal_has_friend_remove()
      ? *_impl_.notify_remarks_.friend_remove_
      : reinterpret_cast< ::chat_ns::NotifyFriendRemove&>(::chat_ns::_NotifyFriendRemove_default_instance_);
}
inline const ::chat_ns::NotifyFriendRemove& NotifyMessage::friend_remove() const {
  // @@protoc_insertion_point(field_get:chat_ns.NotifyMessage.friend_remove)
  return _internal_friend_remove();
}
inline ::chat_ns::NotifyFriendRemove* NotifyMessage::unsafe_arena_release_friend_remove() {
  // @@protoc_insertion_point(field_unsafe_arena_release:chat_ns.NotifyMessage.friend_remove)
  if (_internal_has_friend_remove()) {
    clear_has_notify_remarks();
    ::chat_ns::NotifyFriendRemove* temp = _impl_.notify_remarks_.friend_remove_;
    _impl_.notify_remarks_.friend_remove_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void NotifyMessage::unsafe_arena_set_allocated_friend_remove(::chat_ns::NotifyFriendRemove* friend_remove) {
  clear_notify_remarks();
  if (friend_remove) {
    set_has_friend_remove();
    _impl_.notify_remarks_.friend_remove_ = friend_remove;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:chat_ns.NotifyMessage.friend_remove)
}
inline ::chat_ns::NotifyFriendRemove* NotifyMessage::_internal_mutable_friend_remove() {
  if (!_internal_has_friend_remove()) {
    clear_notify_remarks();
    set_has_friend_remove();
    _impl_.notify_remarks_.friend_remove_ = CreateMaybeMessage< ::chat_ns::NotifyFriendRemove >(GetArenaForAllocation());
  }
  return _impl_.notify_remarks_.friend_remove_;
}
inline ::chat_ns::NotifyFriendRemove* NotifyMessage::mutable_friend_remove() {
  ::chat_ns::NotifyFriendRemove* _msg = _internal_mutable_friend_remove();
  // @@protoc_insertion_point(field_mutable:chat_ns.NotifyMessage.friend_remove)
  return _msg;
}

// .chat_ns.NotifyNewChatSession new_chat_session_info = 5;
inline bool NotifyMessage::_internal_has_new_chat_session_info() const {
  return notify_remarks_case() == kNewChatSessionInfo;
}
inline bool NotifyMessage::has_new_chat_session_info() const {
  return _internal_has_new_chat_session_info();
}
inline void NotifyMessage::set_has_new_chat_session_info() {
  _impl_._oneof_case_[0] = kNewChatSessionInfo;
}
inline void NotifyMessage::clear_new_chat_session_info() {
  if (_internal_has_new_chat_session_info()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.notify_remarks_.new_chat_session_info_;
    }
    clear_has_notify_remarks();
  }
}
inline ::chat_ns::NotifyNewChatSession* NotifyMessage::release_new_chat_session_info() {
  // @@protoc_insertion_point(field_release:chat_ns.NotifyMessage.new_chat_session_info)
  if (_internal_has_new_chat_session_info()) {
    clear_has_notify_remarks();
    ::chat_ns::NotifyNewChatSession* temp = _impl_.notify_remarks_.new_chat_session_info_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.notify_remarks_.new_chat_session_info_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::chat_ns::NotifyNewChatSession& NotifyMessage::_internal_new_chat_session_info() const {
  return _internal_has_new_chat_session_info()
      ? *_impl_.notify_remarks_.new_chat_session_info_
      : reinterpret_cast< ::chat_ns::NotifyNewChatSession&>(::chat_ns::_NotifyNewChatSession_default_instance_);
}
inline const ::chat_ns::NotifyNewChatSession& NotifyMessage::new_chat_session_info() const {
  // @@protoc_insertion_point(field_get:chat_ns.NotifyMessage.new_chat_session_info)
  return _internal_new_chat_session_info();
}
inline ::chat_ns::NotifyNewChatSession* NotifyMessage::unsafe_arena_release_new_chat_session_info() {
  // @@protoc_insertion_point(field_unsafe_arena_release:chat_ns.NotifyMessage.new_chat_session_info)
  if (_internal_has_new_chat_session_info()) {
    clear_has_notify_remarks();
    ::chat_ns::NotifyNewChatSession* temp = _impl_.notify_remarks_.new_chat_session_info_;
    _impl_.notify_remarks_.new_chat_session_info_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void NotifyMessage::unsafe_arena_set_allocated_new_chat_session_info(::chat_ns::NotifyNewChatSession* new_chat_session_info) {
  clear_notify_remarks();
  if (new_chat_session_info) {
    set_has_new_chat_session_info();
    _impl_.notify_remarks_.new_chat_session_info_ = new_chat_session_info;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:chat_ns.NotifyMessage.new_chat_session_info)
}
inline ::chat_ns::NotifyNewChatSession* NotifyMessage::_internal_mutable_new_chat_session_info() {
  if (!_internal_has_new_chat_session_info()) {
    clear_notify_remarks();
    set_has_new_chat_session_info();
    _impl_.notify_remarks_.new_chat_session_info_ = CreateMaybeMessage< ::chat_ns::NotifyNewChatSession >(GetArenaForAllocation());
  }
  return _impl_.notify_remarks_.new_chat_session_info_;
}
inline ::chat_ns::NotifyNewChatSession* NotifyMessage::mutable_new_chat_session_info() {
  ::chat_ns::NotifyNewChatSession* _msg = _internal_mutable_new_chat_session_info();
  // @@protoc_insertion_point(field_mutable:chat_ns.NotifyMessage.new_chat_session_info)
  return _msg;
}

// .chat_ns.NotifyNewMessage new_message_info = 6;
inline bool NotifyMessage::_internal_has_new_message_info() const {
  return notify_remarks_case() == kNewMessageInfo;
}
inline bool NotifyMessage::has_new_message_info() const {
  return _internal_has_new_message_info();
}
inline void NotifyMessage::set_has_new_message_info() {
  _impl_._oneof_case_[0] = kNewMessageInfo;
}
inline void NotifyMessage::clear_new_message_info() {
  if (_internal_has_new_message_info()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.notify_remarks_.new_message_info_;
    }
    clear_has_notify_remarks();
  }
}
inline ::chat_ns::NotifyNewMessage* NotifyMessage::release_new_message_info() {
  // @@protoc_insertion_point(field_release:chat_ns.NotifyMessage.new_message_info)
  if (_internal_has_new_message_info()) {
    clear_has_notify_remarks();
    ::chat_ns::NotifyNewMessage* temp = _impl_.notify_remarks_.new_message_info_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.notify_remarks_.new_message_info_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::chat_ns::NotifyNewMessage& NotifyMessage::_internal_new_message_info() const {
  return _internal_has_new_message_info()
      ? *_impl_.notify_remarks_.new_message_info_
      : reinterpret_cast< ::chat_ns::NotifyNewMessage&>(::chat_ns::_NotifyNewMessage_default_instance_);
}
inline const ::chat_ns::NotifyNewMessage& NotifyMessage::new_message_info() const {
  // @@protoc_insertion_point(field_get:chat_ns.NotifyMessage.new_message_info)
  return _internal_new_message_info();
}
inline ::chat_ns::NotifyNewMessage* NotifyMessage::unsafe_arena_release_new_message_info() {
  // @@protoc_insertion_point(field_unsafe_arena_release:chat_ns.NotifyMessage.new_message_info)
  if (_internal_has_new_message_info()) {
    clear_has_notify_remarks();
    ::chat_ns::NotifyNewMessage* temp = _impl_.notify_remarks_.new_message_info_;
    _impl_.notify_remarks_.new_message_info_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void NotifyMessage::unsafe_arena_set_allocated_new_message_info(::chat_ns::NotifyNewMessage* new_message_info) {
  clear_notify_remarks();
  if (new_message_info) {
    set_has_new_message_info();
    _impl_.notify_remarks_.new_message_info_ = new_message_info;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:chat_ns.NotifyMessage.new_message_info)
}
inline ::chat_ns::NotifyNewMessage* NotifyMessage::_internal_mutable_new_message_info() {
  if (!_internal_has_new_message_info()) {
    clear_notify_remarks();
    set_has_new_message_info();
    _impl_.notify_remarks_.new_message_info_ = CreateMaybeMessage< ::chat_ns::NotifyNewMessage >(GetArenaForAllocation());
  }
  return _impl_.notify_remarks_.new_message_info_;
}
inline ::chat_ns::NotifyNewMessage* NotifyMessage::mutable_new_message_info() {
  ::chat_ns::NotifyNewMessage* _msg = _internal_mutable_new_message_info();
  // @@protoc_insertion_point(field_mutable:chat_ns.NotifyMessage.new_message_info)
  return _msg;
}

inline bool NotifyMessage::has_notify_remarks() const {
  return notify_remarks_case() != NOTIFY_REMARKS_NOT_SET;
}
inline void NotifyMessage::clear_has_notify_remarks() {
  _impl_._oneof_case_[0] = NOTIFY_REMARKS_NOT_SET;
}
inline NotifyMessage::NotifyRemarksCase NotifyMessage::notify_remarks_case() const {
  return NotifyMessage::NotifyRemarksCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace chat_ns

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::chat_ns::NotifyType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::chat_ns::NotifyType>() {
  return ::chat_ns::NotifyType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_notify_2eproto
